// Home page copy. Source of the messaging: 1. Brand Strategy (essence, idea, levers) and the brand guide voice.
// Thai is the lead language (the page is mainly for Thai vendors). Thai copy still needs a native speaker's review.

export const HOME_LANGS = ['th', 'en', 'ko', 'zh', 'ja', 'es', 'fr', 'de'];

export const HOME_LABELS = {
  th: 'ไทย', en: 'English', ko: '한국어', zh: '中文', ja: '日本語', es: 'Español', fr: 'Français', de: 'Deutsch',
};

export const COPY = {
  th: {
    title: 'ChuanLocal · ชวนลูกค้าทุกภาษาเข้าร้าน',
    lang: 'ภาษา',
    headerCta: 'สร้างป้ายฟรี',
    heroTitle: 'ชวนลูกค้าทุกภาษาเข้าร้าน',
    heroSub: 'พิมพ์รายการเป็นภาษาไทย นักท่องเที่ยวสแกนป้ายของคุณ แล้วอ่านเป็นภาษาของตัวเอง โดยมีภาษาไทยอยู่ข้างใต้',
    ctaStart: 'สร้างป้ายฟรี',
    ctaExample: 'ดูตัวอย่าง',
    intro: 'ชวน แปลว่า เชิญชวน ป้ายที่มีแต่ภาษาไทยทำให้ลูกค้าต่างชาติต้องเดา ป้าย ChuanLocal ชวนพวกเขาเข้าร้าน คุณพิมพ์ภาษาไทยเหมือนเดิม ส่วนลูกค้าอ่านเป็นภาษาของตัวเอง',
    s1Over: 'ปัญหา',
    s1Title: 'ลูกค้าที่เดินผ่านไป คือยอดขายที่คุณมองไม่เห็น',
    s1Body: 'นักท่องเที่ยวอ่านป้ายภาษาไทยไม่ออก เลยได้แต่ชี้ เดา หรือเดินผ่านไป วันนั้นดูเหมือนแค่วันที่ร้านเงียบ',
    s2Over: 'ไอเดีย',
    s2Title: 'ภาษาไทยของคุณยังอยู่ ภาษาของลูกค้าอยู่ข้าง ๆ',
    s2Body: 'คุณใช้แค่ภาษาไทย ลูกค้าเห็นรายการเป็นภาษาของตัวเอง และมีชื่อภาษาไทยอยู่ใต้ทุกรายการ ชี้ให้กันดูได้ง่าย ๆ',
    s3Over: 'ที่มา',
    s3Title: 'ทำที่เชียงใหม่ เพื่อเชียงใหม่',
    s3Body: 'สร้างใน 22 ชั่วโมง ที่ Claude Impact Lab Chiang Mai ใช้ฟรีทั้งร้านค้าและลูกค้า ทำขึ้นเพื่อช่วยร้านเล็ก ๆ ในท้องถิ่น ไม่ได้ทำเพื่อหากำไร',
    vOver: 'สำหรับร้านค้า',
    vTitle: 'ป้ายของคุณ พร้อมใช้วันนี้',
    vSteps: [
      ['พิมพ์รายการเป็นภาษาไทย', 'บนมือถือ ไม่ต้องลงแอป ไม่ต้องสมัคร ทุกหน้าเป็นภาษาไทย'],
      ['พิมพ์ป้าย', 'ป้าย A4 หนึ่งแผ่น ติดผนังหรือหน้าร้าน'],
      ['แก้ได้ทุกเมื่อ', 'แตะครั้งเดียว ตั้งรายการพิเศษวันนี้ หรือบอกว่าของหมด'],
    ],
    vNote: 'ใช้ได้ทั้งร้านอาหาร ร้านนวด ทัวร์ และร้านค้า',
    vCta: 'สร้างป้ายฟรี',
    tOver: 'สำหรับนักท่องเที่ยว',
    tTitle: 'เห็นป้ายแล้ว สแกนเลย',
    tSteps: [
      ['มองหาป้าย ChuanLocal', 'ตามร้านอาหาร ร้านค้า และร้านนวด'],
      ['สแกนด้วยกล้องมือถือ', 'ไม่ต้องลงแอป เปิดเป็นภาษาของมือถือเอง'],
      ['ชี้ที่ชื่อภาษาไทย', 'ชื่อภาษาไทยอยู่ใต้ทุกรายการ ชี้ให้ร้านดูเพื่อสั่ง'],
    ],
    tCta: 'ดูตัวอย่าง',
    finalTitle: 'ชวนลูกค้าทุกคนเข้าร้าน',
    finalBody: 'ฟรีทั้งร้านค้าและลูกค้า',
    finalCta: 'สร้างป้ายฟรี',
    footer: 'สร้างที่ Claude Impact Lab Chiang Mai · ฟรีทั้งร้านค้าและลูกค้า',
    photos: 'ภาพถ่ายจาก Unsplash:',
  },
  en: {
    title: 'ChuanLocal · Welcome, in your language',
    lang: 'Language',
    headerCta: 'Make your sign',
    heroTitle: 'Welcome, in your language.',
    heroSub: 'Vendors type their list in Thai. Visitors scan the sign and read it in their own language, with the Thai right underneath.',
    ctaStart: 'Make your sign, free',
    ctaExample: 'See an example',
    intro: 'ชวน (chuan) means “to invite.” A Thai-only sign leaves visitors guessing. A ChuanLocal sign invites them in. Vendors keep writing in Thai; everyone else reads it in theirs.',
    s1Over: 'The problem',
    s1Title: 'A lost sale looks like a quiet day.',
    s1Body: 'Visitors can’t read a Thai-only sign, so they point, guess or walk past. The vendor never sees the sale they lost.',
    s2Over: 'The idea',
    s2Title: 'The vendor’s Thai stays. Yours sits beside it.',
    s2Body: 'Vendors never leave Thai. Visitors read the list in their own language, with the Thai name under every item, so both can point at it.',
    s3Over: 'Where it came from',
    s3Title: 'Made in Chiang Mai, for Chiang Mai.',
    s3Body: 'Built in 22 hours at Claude Impact Lab Chiang Mai. Free for vendors and visitors: it’s here to help local stalls, not to make money.',
    vOver: 'For vendors',
    vTitle: 'Your sign, ready today',
    vSteps: [
      ['Type your list in Thai', 'On your phone. No app, no account. Every screen is in Thai.'],
      ['Print your sign', 'One A4 sign for your wall or counter.'],
      ['Change it any time', 'One tap sets today’s special or marks something sold out.'],
    ],
    vNote: 'Works for food stalls, massage shops, tours and gift shops.',
    vCta: 'Make your sign',
    tOver: 'For visitors',
    tTitle: 'See the sign? Scan it.',
    tSteps: [
      ['Look for the ChuanLocal sign', 'At food stalls, shops and massage places.'],
      ['Scan with your camera', 'No app. It opens in your phone’s language.'],
      ['Point at the Thai', 'The Thai name sits under every item. Show it to order.'],
    ],
    tCta: 'See an example',
    finalTitle: 'Invite every visitor in.',
    finalBody: 'Free for vendors and visitors.',
    finalCta: 'Make your sign',
    footer: 'Built at Claude Impact Lab Chiang Mai. Free for vendors and visitors.',
    photos: 'Photos on Unsplash:',
  },
  ko: {
    title: 'ChuanLocal · 당신의 언어로, 환영합니다',
    lang: '언어',
    headerCta: '간판 만들기',
    heroTitle: '당신의 언어로, 환영합니다.',
    heroSub: '상인은 태국어로 목록을 입력하고, 방문객은 간판을 스캔해 자기 언어로 읽습니다. 태국어는 바로 아래에 그대로 있어요.',
    ctaStart: '무료로 간판 만들기',
    ctaExample: '예시 보기',
    intro: 'ชวน(추안)은 ‘초대하다’라는 뜻입니다. 태국어뿐인 간판은 방문객을 망설이게 하지만, ChuanLocal 간판은 그들을 안으로 초대합니다. 상인은 계속 태국어로 쓰고, 모두가 자기 언어로 읽습니다.',
    s1Over: '문제',
    s1Title: '놓친 손님은 그저 조용한 하루처럼 보입니다.',
    s1Body: '방문객은 태국어 간판을 읽지 못해 가리키거나, 짐작하거나, 그냥 지나칩니다. 상인은 놓친 손님을 알지 못합니다.',
    s2Over: '아이디어',
    s2Title: '상인의 태국어는 그대로, 당신의 언어는 그 옆에.',
    s2Body: '상인은 태국어만 씁니다. 방문객은 자기 언어로 목록을 읽고, 모든 항목 아래 태국어 이름을 함께 가리킬 수 있습니다.',
    s3Over: '시작',
    s3Title: '치앙마이에서, 치앙마이를 위해.',
    s3Body: 'Claude Impact Lab Chiang Mai에서 22시간 만에 만들었습니다. 상인과 방문객 모두 무료이며, 돈이 아니라 동네 가게를 돕기 위해 만들었습니다.',
    vOver: '상인을 위해',
    vTitle: '오늘 바로 쓰는 간판',
    vSteps: [
      ['태국어로 목록 입력', '휴대폰에서. 앱도 계정도 필요 없고, 모든 화면이 태국어입니다.'],
      ['간판 인쇄', '벽이나 계산대에 붙일 A4 한 장.'],
      ['언제든 수정', '한 번 눌러 오늘의 추천을 정하거나 품절을 표시합니다.'],
    ],
    vNote: '음식 노점, 마사지 숍, 투어, 기념품 가게 모두 쓸 수 있어요.',
    vCta: '간판 만들기',
    tOver: '방문객을 위해',
    tTitle: '간판이 보이면 스캔하세요.',
    tSteps: [
      ['ChuanLocal 간판 찾기', '노점, 가게, 마사지 숍에서.'],
      ['카메라로 스캔', '앱 없이 휴대폰 언어로 열립니다.'],
      ['태국어 가리키기', '모든 항목 아래 태국어 이름이 있어요. 보여주고 주문하세요.'],
    ],
    tCta: '예시 보기',
    finalTitle: '모든 방문객을 안으로 초대하세요.',
    finalBody: '상인과 방문객 모두 무료.',
    finalCta: '간판 만들기',
    footer: 'Claude Impact Lab Chiang Mai에서 제작. 상인과 방문객 모두 무료.',
    photos: 'Unsplash 사진:',
  },
  zh: {
    title: 'ChuanLocal · 欢迎，用你的语言',
    lang: '语言',
    headerCta: '制作招牌',
    heroTitle: '欢迎，用你的语言。',
    heroSub: '商家用泰文输入清单，游客扫描招牌，就能用自己的语言阅读，泰文就在下方。',
    ctaStart: '免费制作招牌',
    ctaExample: '查看示例',
    intro: 'ชวน（chuan）的意思是“邀请”。只有泰文的招牌让游客只能猜，ChuanLocal 的招牌则邀请他们进来。商家照常用泰文书写，每个人都能用自己的语言阅读。',
    s1Over: '问题',
    s1Title: '错过的生意，看起来只是冷清的一天。',
    s1Body: '游客看不懂只有泰文的招牌，只能指一指、猜一猜，或者直接走过。商家永远看不到错过的顾客。',
    s2Over: '想法',
    s2Title: '商家的泰文保留，你的语言就在旁边。',
    s2Body: '商家只用泰文。游客用自己的语言阅读清单，每一项下面都有泰文名称，双方都能指着看。',
    s3Over: '由来',
    s3Title: '诞生于清迈，为了清迈。',
    s3Body: '在 Claude Impact Lab Chiang Mai 用 22 小时完成。商家和游客都免费使用，初衷是帮助本地小店，而不是赚钱。',
    vOver: '给商家',
    vTitle: '今天就能用的招牌',
    vSteps: [
      ['用泰文输入清单', '在手机上完成。无需下载应用或注册，所有页面都是泰文。'],
      ['打印招牌', '一张 A4，贴在墙上或柜台。'],
      ['随时修改', '一键设置今日推荐，或标记已售完。'],
    ],
    vNote: '适用于小吃摊、按摩店、旅游团和礼品店。',
    vCta: '制作招牌',
    tOver: '给游客',
    tTitle: '看到招牌？扫一扫。',
    tSteps: [
      ['寻找 ChuanLocal 招牌', '在小吃摊、商店和按摩店。'],
      ['用相机扫描', '无需应用，自动以手机语言打开。'],
      ['指着泰文点单', '每一项下面都有泰文名称，指给店家看即可。'],
    ],
    tCta: '查看示例',
    finalTitle: '邀请每一位游客进来。',
    finalBody: '商家和游客都免费。',
    finalCta: '制作招牌',
    footer: '诞生于 Claude Impact Lab Chiang Mai。商家和游客都免费。',
    photos: 'Unsplash 照片：',
  },
  ja: {
    title: 'ChuanLocal · ようこそ、あなたの言葉で',
    lang: '言語',
    headerCta: '看板をつくる',
    heroTitle: 'ようこそ、あなたの言葉で。',
    heroSub: 'お店はタイ語でリストを入力。訪れた人は看板をスキャンして、自分の言葉で読めます。タイ語はそのすぐ下に。',
    ctaStart: '無料で看板をつくる',
    ctaExample: '例を見る',
    intro: 'ชวน（チュアン）は「招く」という意味。タイ語だけの看板では、訪れた人は推測するしかありません。ChuanLocal の看板は、その人たちを招き入れます。お店はこれまでどおりタイ語で書き、誰もが自分の言葉で読めます。',
    s1Over: '課題',
    s1Title: '逃したお客さんは、ただの静かな一日に見える。',
    s1Body: 'タイ語だけの看板は読めないので、指さしたり、推測したり、通り過ぎたり。お店は逃したお客さんに気づけません。',
    s2Over: 'アイデア',
    s2Title: 'お店のタイ語はそのまま。あなたの言葉はその隣に。',
    s2Body: 'お店はタイ語だけで大丈夫。訪れた人は自分の言葉でリストを読み、すべての品のタイ語名を一緒に指させます。',
    s3Over: 'はじまり',
    s3Title: 'チェンマイで、チェンマイのために。',
    s3Body: 'Claude Impact Lab Chiang Mai で 22 時間でつくりました。お店も訪れる人も無料。利益ではなく、地元の小さなお店を支えるためのものです。',
    vOver: 'お店の方へ',
    vTitle: '今日から使える看板',
    vSteps: [
      ['タイ語でリストを入力', 'スマホで。アプリもアカウントも不要、画面はすべてタイ語です。'],
      ['看板を印刷', '壁やカウンターに貼る A4 一枚。'],
      ['いつでも変更', 'ワンタップで本日のおすすめや売り切れを表示。'],
    ],
    vNote: '屋台、マッサージ店、ツアー、おみやげ店に使えます。',
    vCta: '看板をつくる',
    tOver: '訪れる方へ',
    tTitle: '看板を見つけたら、スキャン。',
    tSteps: [
      ['ChuanLocal の看板を探す', '屋台、お店、マッサージ店で。'],
      ['カメラでスキャン', 'アプリ不要。スマホの言語で開きます。'],
      ['タイ語を指さす', 'すべての品の下にタイ語名があります。見せて注文しましょう。'],
    ],
    tCta: '例を見る',
    finalTitle: 'すべての人を、お店に招こう。',
    finalBody: 'お店も訪れる人も無料。',
    finalCta: '看板をつくる',
    footer: 'Claude Impact Lab Chiang Mai で誕生。お店も訪れる人も無料。',
    photos: 'Unsplash の写真：',
  },
  es: {
    title: 'ChuanLocal · Bienvenido, en tu idioma',
    lang: 'Idioma',
    headerCta: 'Crea tu cartel',
    heroTitle: 'Bienvenido, en tu idioma.',
    heroSub: 'Los vendedores escriben su lista en tailandés. Los visitantes escanean el cartel y la leen en su propio idioma, con el tailandés justo debajo.',
    ctaStart: 'Crea tu cartel gratis',
    ctaExample: 'Ver un ejemplo',
    intro: 'ชวน (chuan) significa «invitar». Un cartel solo en tailandés deja a los visitantes adivinando. Un cartel de ChuanLocal los invita a entrar. Los vendedores siguen escribiendo en tailandés; los demás lo leen en su idioma.',
    s1Over: 'El problema',
    s1Title: 'Una venta perdida parece un día tranquilo.',
    s1Body: 'Los visitantes no pueden leer un cartel solo en tailandés, así que señalan, adivinan o pasan de largo. El vendedor nunca ve la venta que perdió.',
    s2Over: 'La idea',
    s2Title: 'El tailandés del vendedor se queda. Tu idioma va a su lado.',
    s2Body: 'Los vendedores nunca dejan el tailandés. Los visitantes leen la lista en su idioma, con el nombre en tailandés bajo cada artículo, para que ambos puedan señalarlo.',
    s3Over: 'De dónde viene',
    s3Title: 'Hecho en Chiang Mai, para Chiang Mai.',
    s3Body: 'Creado en 22 horas en Claude Impact Lab Chiang Mai. Gratis para vendedores y visitantes: está para ayudar a los puestos locales, no para ganar dinero.',
    vOver: 'Para vendedores',
    vTitle: 'Tu cartel, listo hoy',
    vSteps: [
      ['Escribe tu lista en tailandés', 'En tu teléfono. Sin app ni cuenta; todas las pantallas están en tailandés.'],
      ['Imprime tu cartel', 'Una hoja A4 para la pared o el mostrador.'],
      ['Cámbialo cuando quieras', 'Un toque para el especial del día o para marcar algo agotado.'],
    ],
    vNote: 'Sirve para puestos de comida, masajes, tours y tiendas de regalos.',
    vCta: 'Crea tu cartel',
    tOver: 'Para visitantes',
    tTitle: '¿Ves el cartel? Escanéalo.',
    tSteps: [
      ['Busca el cartel de ChuanLocal', 'En puestos, tiendas y casas de masaje.'],
      ['Escanea con la cámara', 'Sin app. Se abre en el idioma de tu teléfono.'],
      ['Señala el tailandés', 'El nombre en tailandés está bajo cada artículo. Muéstralo para pedir.'],
    ],
    tCta: 'Ver un ejemplo',
    finalTitle: 'Invita a pasar a cada visitante.',
    finalBody: 'Gratis para vendedores y visitantes.',
    finalCta: 'Crea tu cartel',
    footer: 'Hecho en Claude Impact Lab Chiang Mai. Gratis para vendedores y visitantes.',
    photos: 'Fotos en Unsplash:',
  },
  fr: {
    title: 'ChuanLocal · Bienvenue, dans votre langue',
    lang: 'Langue',
    headerCta: 'Créer mon affiche',
    heroTitle: 'Bienvenue, dans votre langue.',
    heroSub: 'Les vendeurs écrivent leur liste en thaï. Les visiteurs scannent l’affiche et la lisent dans leur langue, avec le thaï juste en dessous.',
    ctaStart: 'Créer mon affiche gratuite',
    ctaExample: 'Voir un exemple',
    intro: 'ชวน (chuan) veut dire « inviter ». Une affiche uniquement en thaï laisse les visiteurs deviner. Une affiche ChuanLocal les invite à entrer. Les vendeurs continuent d’écrire en thaï ; chacun lit dans sa propre langue.',
    s1Over: 'Le problème',
    s1Title: 'Une vente perdue ressemble à une journée calme.',
    s1Body: 'Les visiteurs ne savent pas lire une affiche uniquement en thaï : ils montrent du doigt, devinent ou passent leur chemin. Le vendeur ne voit jamais la vente perdue.',
    s2Over: 'L’idée',
    s2Title: 'Le thaï du vendeur reste. Votre langue se place à côté.',
    s2Body: 'Les vendeurs ne quittent jamais le thaï. Les visiteurs lisent la liste dans leur langue, avec le nom thaï sous chaque article, pour pouvoir le montrer tous les deux.',
    s3Over: 'D’où ça vient',
    s3Title: 'Fait à Chiang Mai, pour Chiang Mai.',
    s3Body: 'Créé en 22 heures au Claude Impact Lab Chiang Mai. Gratuit pour les vendeurs et les visiteurs : pour aider les échoppes locales, pas pour gagner de l’argent.',
    vOver: 'Pour les vendeurs',
    vTitle: 'Votre affiche, prête aujourd’hui',
    vSteps: [
      ['Écrivez votre liste en thaï', 'Sur votre téléphone. Sans appli ni compte ; tous les écrans sont en thaï.'],
      ['Imprimez votre affiche', 'Une feuille A4 pour le mur ou le comptoir.'],
      ['Modifiez-la à tout moment', 'Un geste pour la suggestion du jour ou pour indiquer « épuisé ».'],
    ],
    vNote: 'Pour les stands de cuisine, les salons de massage, les excursions et les boutiques.',
    vCta: 'Créer mon affiche',
    tOver: 'Pour les visiteurs',
    tTitle: 'Vous voyez l’affiche ? Scannez-la.',
    tSteps: [
      ['Repérez l’affiche ChuanLocal', 'Dans les échoppes, boutiques et salons de massage.'],
      ['Scannez avec l’appareil photo', 'Sans appli. Elle s’ouvre dans la langue de votre téléphone.'],
      ['Montrez le thaï', 'Le nom thaï est sous chaque article. Montrez-le pour commander.'],
    ],
    tCta: 'Voir un exemple',
    finalTitle: 'Invitez chaque visiteur à entrer.',
    finalBody: 'Gratuit pour les vendeurs et les visiteurs.',
    finalCta: 'Créer mon affiche',
    footer: 'Créé au Claude Impact Lab Chiang Mai. Gratuit pour les vendeurs et les visiteurs.',
    photos: 'Photos sur Unsplash :',
  },
  de: {
    title: 'ChuanLocal · Willkommen, in Ihrer Sprache',
    lang: 'Sprache',
    headerCta: 'Schild erstellen',
    heroTitle: 'Willkommen, in Ihrer Sprache.',
    heroSub: 'Händler schreiben ihre Liste auf Thai. Besucher scannen das Schild und lesen sie in ihrer eigenen Sprache – das Thai steht direkt darunter.',
    ctaStart: 'Kostenloses Schild erstellen',
    ctaExample: 'Beispiel ansehen',
    intro: 'ชวน (chuan) heißt „einladen“. Ein Schild nur auf Thai lässt Besucher raten. Ein ChuanLocal-Schild lädt sie ein. Händler schreiben weiter auf Thai; alle anderen lesen in ihrer Sprache.',
    s1Over: 'Das Problem',
    s1Title: 'Ein verlorener Verkauf sieht aus wie ein ruhiger Tag.',
    s1Body: 'Besucher können ein Schild nur auf Thai nicht lesen. Sie zeigen, raten oder gehen vorbei. Der Händler sieht den verlorenen Verkauf nie.',
    s2Over: 'Die Idee',
    s2Title: 'Das Thai bleibt. Ihre Sprache steht daneben.',
    s2Body: 'Händler bleiben beim Thai. Besucher lesen die Liste in ihrer Sprache, mit dem thailändischen Namen unter jedem Eintrag – so können beide darauf zeigen.',
    s3Over: 'Woher es kommt',
    s3Title: 'Gemacht in Chiang Mai, für Chiang Mai.',
    s3Body: 'In 22 Stunden beim Claude Impact Lab Chiang Mai entstanden. Kostenlos für Händler und Besucher – um lokalen Ständen zu helfen, nicht um Geld zu verdienen.',
    vOver: 'Für Händler',
    vTitle: 'Ihr Schild, heute fertig',
    vSteps: [
      ['Liste auf Thai eingeben', 'Auf dem Handy. Ohne App und ohne Konto; alle Seiten sind auf Thai.'],
      ['Schild drucken', 'Ein A4-Blatt für Wand oder Theke.'],
      ['Jederzeit ändern', 'Ein Tipp für das Tagesangebot oder „ausverkauft“.'],
    ],
    vNote: 'Für Essensstände, Massagesalons, Touren und Souvenirläden.',
    vCta: 'Schild erstellen',
    tOver: 'Für Besucher',
    tTitle: 'Schild gesehen? Scannen.',
    tSteps: [
      ['ChuanLocal-Schild finden', 'An Ständen, in Läden und Massagesalons.'],
      ['Mit der Kamera scannen', 'Ohne App. Öffnet sich in der Sprache Ihres Handys.'],
      ['Auf das Thai zeigen', 'Unter jedem Eintrag steht der thailändische Name. Zeigen Sie darauf, um zu bestellen.'],
    ],
    tCta: 'Beispiel ansehen',
    finalTitle: 'Laden Sie jeden Besucher ein.',
    finalBody: 'Kostenlos für Händler und Besucher.',
    finalCta: 'Schild erstellen',
    footer: 'Entstanden beim Claude Impact Lab Chiang Mai. Kostenlos für Händler und Besucher.',
    photos: 'Fotos auf Unsplash:',
  },
};

// Free Unsplash photos (Unsplash License, not Unsplash+). Candid, not staged.
export const PHOTOS = {
  hero: { id: 'photo-1552912470-ee2e96439539', by: 'Vernon Raineil Cenzon', page: 'https://unsplash.com/photos/QAkqxrH6mvc' },
  problem: { id: 'photo-1662694385995-b3509ea9592b', by: 'Markus Winkler', page: 'https://unsplash.com/photos/rp_De2z7Wgc' },
  idea: { id: 'photo-1752147562751-79b8fe5069a1', by: 'Polina Kuzovkova', page: 'https://unsplash.com/photos/qrdagj7ObA0' },
  origin: { id: 'photo-1568649479452-4fa420ed8256', by: 'YingChu Chen', page: 'https://unsplash.com/photos/QMGGhIkljKo' },
  vendors: { id: 'photo-1758346972369-6f3e57961085', by: 'Kelvin Zyteng', page: 'https://unsplash.com/photos/FU2GsnrycLk' },
  visitors: { id: 'photo-1550487221-3750d2cb0b3c', by: 'Waranont (Joe)', page: 'https://unsplash.com/photos/s3E4flC32RE' },
  final: { id: 'photo-1750635409983-78ca6a8cf324', by: 'Kaden Taylor', page: 'https://unsplash.com/photos/k8dwH-poJ2c' },
};
